# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- azure-pipelines

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-javascript-docker'
  dockerHub: 'ChyzhykACR'
  login: chyzhykcr.azurecr.io

steps:

  - task: Docker@2
    inputs:
      containerRegistry: 'ChyzhykACR'
      repository: '$(login)/$(imageName)'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'